.catalog:
  name: "Sinopia"
  version: "v0.2"
  description: ""
  uuid: Sinopia-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "VOLUMNE"
      type: "string"
      label: "VOLUMNE"
      required: true
      description: |
                Path to the Volumne file
      default: "/opt/sinopia"
    - variable: "PORT"
      type: "int"
      required: true
      label: "Port"
      description: |
                Port on your Host System
      default: 4873


sinopia:
