jenkins-primary:
  image: "jenkinsci/jenkins:2.0-rc-1"
  ports:
    - "9000:8080"
  labels:
    io.rancher.sidekicks: jenkins-plugins
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - jenkins-plugins
    - /jenkins:/var/jenkins_home
  volume-driver: convoy-gluster
  entrypoint: /usr/share/jenkins/rancher/jenkins.sh
jenkins-plugins:
  image: rancher/jenkins-plugins:v0.1.1
