wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
    - jenkins:/var/www/html
  volume_driver: convoy-gluster

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
