confluence:
  ports:
  - ${PORT}:8090
  image: cptactionhank/atlassian-confluence:5.9.12
  volumes:
    - ${CONFLUENCE_DATA_PATH}:/var/atlassian/confluence
    - ${CONFLUENCE_LOG_PATH}:/opt/atlassian/confluence/logs
  links:
  	- "postgres"
postgres:
  ports:
    - ${PGSQLPORT}:5432
  image: postgres:9.5.3
  volumes:
    - ${PGSQL_DATA_PATH}:/var/lib/postgresql/data
  environment:
    - "POSTGRES_USER=confluence"
    - "POSTGRES_PASSWORD=${PGSQL_PASSWORD}"