registry:
  restart: always
  image: registry:2.4
  ports:
    - ${PORT}:5000
  environment:
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ${PATH}/data:/var/lib/registry
    - ${PATH}/auth:/auth